version: '3'
services:
  mongo:
    container_name: test-web-mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: luccrouser
      MONGO_INITDB_ROOT_PASSWORD: trustedx9cv84
    ports:
      - '27017:27017'
    volumes:
      - ./storage/mongo:/data/db



